### PR TITLE
Update for recent reorganizations.

### PR DESCRIPTION
**Pull request by atgeirr**
No functional changes.

### CODE REVIEW

**Comment by bska** [comment]
You just ensured that downstream clients (ResInsight) will have to get a new version of opm-common as part of their patch release.  Unfortunate timing.

**Comment by atgeirr** [comment]
> You just ensured that downstream clients (ResInsight) will have to get a new version of opm-common as part of their patch release. Unfortunate timing.

I suggest branching off to resolve this.

**Comment by atgeirr** [comment]
Actually, on second thought it should not be necessary to do anything, as this only affects the example/ code, which is not used by ResInsight (only the library parts are).

**Comment by akva2** [comment]
If a release is built against head of a repo, the problem is not here..

**Pull request merged**
