### PR TITLE
Move ECL utilities to separate file.

### PR DESCRIPTION
**Pull request by atgeirr**
Makes it possible to use these tools from new classes.

Note that the new header is *not* made public (installed).

### CODE REVIEW

**Comment by bska** [comment]
Why?  I don't want anything other than `ECLGraph` to use these things.  They are supposed to be entirely internal to the implementation of that class.

**Comment by atgeirr** [comment]
Because they are useful for writing a class to read well fluxes.

**Comment by bska** [comment]
> Because they are useful for writing a class to read well fluxes.

No they're not.  About the only thing that's generally applicable here is `ECL::loadFile()`.  The rest is **very** specific to the construction of the `ECLGraph`.

**Comment by atgeirr** [comment]
I think the ScatterMap might be useful (also adding an accessor for it in ECLGraph).

**Comment by atgeirr** [comment]
Closed after offline discussion.

**Pull request closed without merging**
