### PR TITLE
Flux calculations (again)

### PR DESCRIPTION
**Pull request by atgeirr**
Replaces #30, as I had trouble rebasing that for some reason.

### CODE REVIEW

**Comment by atgeirr** [comment]
I believe this is ready to be reviewed now. The code is producing NaNs, but it is unclear if that is due to faults in reading the pressure field or introduced here. The first step after this should be to verify the pressure reading and expand its unit test, then add a unit test for the current functionality.

**Comment by bska** [comment]
> The code is producing NaNs, but it is unclear if that is due to faults in reading the pressure field or introduced here.

I don't see that symptom.  Could you be a bit more specific?  What quantity (or quantities?) contain NaN?  In what context?

**Comment by atgeirr** [comment]
> I don't see that symptom. Could you be a bit more specific? What quantity (or quantities?) contain NaN? In what context?

When executing
```
computeToFandTracers case=SIMPLE step=5 compute_fluxes=true
```
the result contains NaNs.

**Comment by atgeirr** [comment]
Existing functionality is unaffected though, sorry if that was not clear.

**Comment by bska** [comment]
I think this is okay, and I'll merge into master.  Thanks a lot.

**Pull request merged**
