### PR TITLE
Guard negative index calculations

### PR DESCRIPTION
**Pull request by magnesj**
Testing on dual porosity models revealed existence of negative 0-based indices. Add code to guard for negative indices.

### CODE REVIEW

**Review by bska — COMMENTED** [review]
Does this mean that `tabdims[ StartIX ] == 0` or is it actually negative for the models in question?  And if the start index is zero, does the corresponding table have a positive dimension or is that zero too?

**Comment by bska** [comment]
> Does this mean that `tabdims[ StartIX ] == 0` or is it actually negative for the models in question?

And another thing: Did this issue present in the case of result sets created by ECLIPSE 100 or by ECLIPSE 300?

**Comment by magnesj** [comment]
This is a dual porosity model created by 6X, so it might be an issue in their export.

> Does this mean that `tabdims[ StartIX ] == 0` or is it actually negative for the models in question? And if the start index is zero, does the corresponding table have a positive dimension or is that zero too?

Yes, tabdims[ StartIX ] == 0

> Does this mean that tabdims[ StartIX ] == 0 or is it actually negative for the models in question? And if the start index is zero, does the corresponding table have a positive dimension or is that zero too?

The corresponding table has values that look OK.

**Comment by magnesj** [comment]
This is probably an export error produced by https://ridgewaykite.com/6x/ 
I will also notify them of this issue.

Anyway, I would appreciate if flowdiagnostics do not crash if this situation occurs, and an log message/exception can be useful. Crash in a dependent library is always unfortunate for an application using this library.

**Comment by bska** [comment]
> > Does this mean that `tabdims[ StartIX ] == 0` or is it actually negative for the models in question?
> 
> Yes, `tabdims[ StartIX ] == 0`
> 
> > And if the start index is zero, does the corresponding table have a positive dimension or is that zero too?
> 
> The corresponding table has values that look OK.

That's weird

> This is probably an export error produced by https://ridgewaykite.com/6x/

Right, that seems likely.

> I would appreciate if flowdiagnostics do not crash if this situation occurs, and an log message/exception can be useful.

Sure.  I think that's the only safe course of action.  If the start index is zero, then I'm not inclined to trust any of the other values and I think it'd be better to guard against this using logic of the form
```C++
start = tabdims[ StartIX ] - 1;
if (start < 0) {
    throw std::invalid_argument {
        "Invalid table offset for <Keyword>"
    };
}
```
rather than to hide it in a `max()` call and possibly run into issues that are harder to diagnose later.

**Comment by magnesj** [comment]
Investigated new dataset received from 6X, and the previously invalid indices are now correct. Update PR to throw invalid_argument if invalid data is detected.

**Comment by bska** [comment]
> Investigated new dataset received from 6X, and the previously invalid indices are now correct. Update PR to throw invalid_argument if invalid data is detected.

Much appreciated.  This version looks good to me so I'll merge into master.

**Pull request merged**
