### PR TITLE
changed: put prereqs in module itself 

### PR DESCRIPTION
**Pull request by akva2**
Upstream: https://github.com/OPM/opm-common/pull/304

### CODE REVIEW

**Comment by bska** [comment]
I like it.  A lot.  Just one question if I may: Why do we need to enable C?  There is no C code in this module.

**Comment by akva2** [comment]
see first prereq.

**Comment by akva2** [comment]
it builds fine if i remove the C99 prereq so suspect that it's a c&p entry. shall i remove it?

**Comment by bska** [comment]
> it builds fine if i remove the C99 prereq

Ah, right.  I suspected as much but it's good to have confirmation.

> so suspect that it's a c&p entry.

You're definitely right about that.

> shall i remove it?

Yes please.

**Comment by akva2** [comment]
as i have no maintainer status here; upstream PR has been merged, please merge this to restore build of this module.

**Pull request merged**
