### PR TITLE
Use ParameterGroup to obtain necessary input parameters.

### PR DESCRIPTION
**Pull request by atgeirr**
This simplifies the code, yet keeps the option to specify just a case name or to give init, grid and restart filenames explicitly.

A tiny drawback: FEGRID or FINIT must be specified explicitly if required (EGRID and INIT used by default).

### CODE REVIEW

**Comment by bska** [comment]
To be honest, I think this patch simplifies the code too much.  I'd prefer a mix of the original approach that relied on positional parameters only and the new one that leverages the `ParameterGroup`.  For instance, if we keep but adapt the `gridFile()` &c functions to something like
```C++
boost::filesystem::path
gridFile(const Opm::ParameterGroup& params)
{
    const auto cas = params.getDefault<std::string>("casename", "@@@ERROR: CASE-NOT-SUPPLIED");
    const auto gfile = params.getDefault("grid", cas);

    return deriveFileName(gfile, { ".EGRID", ".FEGRID", ".GRID", ".FGRID" });
}
```
then we keep the flexible filename specifications and gain a flexible way of passing parameters.  Similar for the other objects.

**Comment by atgeirr** [comment]
I'm with you, but something's not quite right with your suggestion: we cannot actually specify the grid filename completely, but only it's case name. Then the first match in the list will be returned. So if we wanted the .FEGRID and there is an .EGRID, we cannot do that.

I guess your main goal is to keep the automatic finding of an .FEGRID file (if it exists)? I can try to provide a fix.

**Comment by bska** [comment]
> but something's not quite right with your suggestion: we cannot actually specify the grid filename completely, but only it's case name.

Well, if we add
```C++
if (isFile(file)) { return file; }
```
to `deriveFileName()` **prior** to the extension loop, then that is handled too.

**Comment by atgeirr** [comment]
Revised. I think the new version is quite clear: either you specify the filename, or we try to derive it.

**Comment by bska** [comment]
> I think the new version is quite clear

Sort of.  I think it puts too many low-level objects and their interrelated logic into `main()`.  That's likely to obscure the overall purpose going forward.  That said, I'll merge this now and we can refactor it when the need arises.

**Pull request merged**
